use HIP-VPLS;

CREATE TABLE IF NOT EXISTS Users (
	id INT PRIMARY KEY AUTOINCREMENT,
	username VAHRCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	salt VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Devices (
	id INT PRIMARY KEY AUTOINCREMENT,
	hit VARCHAR(100) NOT NULL,
	ip VARCHAR(100) NOT NULL,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Mesh (
	id INT PRIMARY KEY AUTOINCREMENT,
	device_1_id INT NOT NULL,
	device_2_ID INT NOT NULL,
	name VARCHAR(100) NOT NULL DEFAULT ""
);

CREATE TABLE IF NOT EXISTS Firewall (
	id INT PRIMARY KEY AUTOINCREMENT,
	device_id INT NOT NULL,
	rule VARCHAR(100) NOT NULL DEFAULT "allow"
);
