d1<-scan("download-null.txt")
d2<-scan("upload-null.txt")
d3<-scan("download-aes.txt")
d4<-scan("upload-aes.txt")

mean(d1)
mean(d2)
mean(d3)
mean(d4)

pdf("final.pdf")
par(mfrow=c(2,2))
hist(d1, col="dark red", breaks=20, main="Download NULL encryption", xlim=c(0, max(max(d2), max(d1), max(d3), max(d4))), xlab="Throughput, Mbits/s")
grid(lwd=1, col="black", lty=1)
hist(d2, col="dark blue", breaks=20, main="Upload NULL encryption", xlim=c(0, max(max(d2), max(d1), max(d3), max(d4))), xlab="Throughput, Mbits/s")
grid(lwd=1, col="black", lty=1)
hist(d3, col="dark red", breaks=20, main="Download hardware AES encryption", xlim=c(0, max(max(d2), max(d1), max(d3), max(d4))), xlab="Throughput, Mbits/s")
grid(lwd=1, col="black", lty=1)
hist(d4, col="dark blue", breaks=20, main="Upload hardware AES encryption", xlim=c(0, max(max(d2), max(d1), max(d3), max(d4))), xlab="Throughput, Mbits/s")
grid(lwd=1, col="black", lty=1)
dev.off()
